### PR TITLE
Add function for retrieving cached glyph positions

### PR DESCRIPTION
**Pull request by Xaeroxe**
As discussed on gitter.

This PR adds functions to allow downstream users to use the cached glyph positions and avoid having to re-compute the positions themselves.

### CODE REVIEW

**Comment by Xaeroxe** [comment]
(A minor version release following merging of this PR would be helpful if you don't mind)

**Comment by alexheretic** [comment]
Thanks @Xaeroxe looks good! I think I'd prefer to simply call the methods `glyphs`,  rather than `cached_glyphs` as use of the cache is an implementation detail, and can be disabled with _cache_glyph_positioning_.

Ie `pixel_bounds` doesn't mention the cache in the name, but putting this in the documentation of course makes sense.

**Comment by alexheretic** [comment]
I would normally just push small changes to the pr branches to try to minimise delays but I don't seem to have that ability here.

**Comment by vitvakatu** [comment]
PR initiator should check "Allow edits from maintainers" to, basically, allow you to make changes.

**Comment by Xaeroxe** [comment]
I made the change. It's curious that you couldn't make it, as I can see the box checked right now.

**Comment by alexheretic** [comment]
Oh yeah I could do it using the online client, so I must have messed up something using cli

**Comment by Xaeroxe** [comment]
Thanks for fixing my call there @alexheretic.  I was trying to get it in before you went to sleep since we seem to be in different time zones and clearly I wasn't thorough enough.

**Comment by alexheretic** [comment]
Np, thanks again for the PR @Xaeroxe I'll release this as `0.6.1`

**Pull request merged**
